"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 750

format = """
$directory\
$package\
$nodejs\
$ruby\
$golang\
$git_branch\
$git_state\
$git_status\
$git_metrics\
[](prev_bg)\
$fill\
$kubernetes
$character
"""

right_format = """$all"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
style = "fg:mantle bg:blue"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[package]
style = "dimmed fg:mantle bg:prev_bg"
format = '[\($version\) ]($style)'

[nodejs]
style = "dimmed fg:mantle bg:green"
not_capable_style = "fg:bold red bg:green"
symbol = "⬢"
format = "[ ](fg:prev_bg bg:green)[$symbol ($version )]($style)"

[ruby]
style = "dimmed fg:mantle bg:maroon"
symbol = "◆"
format = "[ ](fg:prev_bg bg:maroon)[$symbol ($version )]($style)"

[golang]
style = "dimmed fg:mantle bg:sapphire"
not_capable_style = "fg:bold red bg:sapphire"
format = "[ ](fg:prev_bg bg:sapphire)[$symbol ($version )]($style)"

[git_branch]
style = "fg:text bg:surface0"
format = "[ ](fg:prev_bg bg:surface0)[$symbol$branch(:$remote_branch) ]($style)"

[git_state]
style = "fg:yellow bg:surface0"
format = "[$state( $progress_current/$progress_total) ]($style)"

[git_status]
style = "fg:text bg:surface0"
conflicted = "!=="
ahead = " ⬆"
behind = " ⬇"
diverged = " ⬍"
up_to_date = ""
untracked = "[✭](fg:yellow bg:surface0)"
stashed = "[≡](fg:green bg:surface0)"
modified = "[✹](fg:blue bg:surface0)"
staged = '[✚](fg:green bg:surface0)'
renamed = "➜"
deleted = "[✖](fg:red bg:surface0)"
format = "[$all_status ($ahead_behind )]($style)"

[git_metrics]
disabled = false
added_style = "fg:green bg:surface0"
deleted_style= "fg:maroon bg:surface0"
format = "[(+$added)]($added_style)[(-$deleted) ]($deleted_style)"

[fill]
symbol = " "

[kubernetes]
disabled = false
style = "lavender"
format = '[$symbol$context \($namespace\) ]($style)'

[aws]
disabled = true

[cmd_duration]
disabled = true
